<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Praveen" failures="2" tests="4" name="Error Test" time="28.655" errors="0" timestamp="2024-03-18T11:26:59 EDT">
  <testcase classname="Automation4ME.tests.ErrorValidationtest" name="Errors" time="0.897">
    <skipped/>
  </testcase> <!-- Errors -->
  <testcase classname="Automation4ME.tests.ErrorValidationtest" name="Errors" time="0.669">
    <skipped/>
  </testcase> <!-- Errors -->
  <testcase classname="Automation4ME.tests.ErrorValidationtest" name="Errors" time="0.687">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Automation4ME.tests.ErrorValidationtest.Errors(ErrorValidationtest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Errors -->
  <testcase classname="Automation4ME.tests.ErrorValidationtest" name="Errors" time="0.6">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Automation4ME.tests.ErrorValidationtest.Errors(ErrorValidationtest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Errors -->
</testsuite> <!-- Error Test -->
